common:
    model:
        type: tsn # tsm, slowfast
        backbone: proxyless_mobile

        num_segments: 3
        num_class: 152
        dropout: 0.8
        pretrained: True
    
        kwargs:
            bn_group_size: 1
            bn_sync_stats: True
    
    augmentation:
        input_size: 224
        test_resize: 256
        # colorjitter: [0.2, 0.2, 0.2, 0.1]
        # colorold: True
        # mix_up: 1.0

    workers: 3
    batch_size: 64

    lr_scheduler:
        type: COSINE 
        base_lr: 0.01
        warmup_steps: 250
        warmup_lr: 0.04
        min_lr: 0.0
        max_iter: 15010

    momentum: 0.9
    weight_decay: 0.0001
    nesterov: True

    val_freq: 250
    print_freq: 10

    train_root: /
    train_source: /mnt/lustre/share/jipuzhao/benchmarks/douyin/douyin_v5/lists/rgb_train.txt
    val_root: /
    val_source: /mnt/lustre/share/jipuzhao/benchmarks/douyin/douyin_v5/lists/rgb_val.txt
